---
title: "Meetup_customer_segmentation"
author: "Will Bidstrup"
date: "12 October 2016"
output: html_document
---

# Setup 
```{r}
# Set WD
setwd("/Users/wbidst/Documents/test-repo")

# Install packages
install.packages("tidyverse", repos = "http://cran.rstudio.com/")
library(tidyverse)

```


# Load
```{r load}
data <- read.csv("customer_details_dataset.csv", stringsAsFactors = FALSE)
```

Useful code for read.csv `data1 <- read.csv(file.choose())`

# Explore
```{r explore}
# Change to factor
data[, c(3, 6)] <- lapply(data[, c(3, 6)], function(x) { as.factor(x) } )

# Quick visuals
ggplot(data = data, aes(x = Age, y = Spend_12M, col = Gender)) +
  geom_point(alpha = 0.2, size = 2, position = "jitter") +
  facet_wrap(~ Region, nrow = 2)

ggplot(data = data, aes(x = Age, y = Spend_12M, col = Children)) +
  geom_point(alpha = 0.2, size = 2, position = "jitter") +
  facet_wrap(~ Region, nrow = 2)

```



```{r clustering}
data_k <- kmeans(data[, c(2, 4, 5)], 3)

# Add kmeans category to data
data$kmean <- data_k[["cluster"]]

data$kmean <- as.factor(data$kmean)

# Plot

ggplot(data = data, aes(x = Age, y = Spend_12M, col = kmean)) +
   geom_point(alpha = 0.2, size = 2, position = "jitter") +
  facet_wrap(~Region, nrow = 2)
```




